const express = require('express')
const router = express.Router()
const bcrypt = require('bcryptjs')
const User = require('../../models/User')
const validateLoginInput = require('../../validation/login')
const validateRegisterInput = require('../../validation/register')
const jwt = require('jsonwebtoken');
const keys = require('../../config/keys')

// routes
router.get('/test', (req, res) => res.json({ msg: 'This is the users route' }))
// register
router.post('/register', (req, res) => {
  // Check if the email has already been registered 
  const { email, username, password } = req.body
  const { errors, isValid } = validateRegisterInput(req.body)

  if (!isValid) return res.status(400).json(errors)

  User.findOne({ username })
    .then(user => {
      // Try to find a user that is registered with the same username, if the user's email exists in the database then we send an error 
      if (user) return res.status(400).json({ username: 'A user has already registered with this username' })
      const newUser = new User({ username, email, password })
      // User bcrypt to hash the users password from the req.body, this is done so we do not store the password into the database 
      bcrypt.genSalt(10, (err, salt) => {
        bcrypt.hash(newUser.password, salt, (err, hash) => {
          if (err) throw err
          // Set the password of the newUser object as a hash generated by bcrypt
          newUser.password = hash
          newUser.save()
            .then(user => {
              const payload = { id: user.id, username: user.username }
              jwt.sign(payload, keys.secretOrKey, { expiresIn: 3600 },
                (err, token) => res.json({ success: true, token: 'Bearer ' + token })
              )
            })
            .catch(err => console.log(err))
        })
      })
    })
})

// login
router.post('/login', (req, res) => {
  const { errors, isValid } = validateLoginInput(req.body)
  const { username, password } = req.body 
  // isValid is coming from validateLoginInput so we validate the user's login information and make sure that the user is entering valid text
  if (!isValid) return res.status(400).json(errors)

  User.findOne({ username })
    .then(user => {
      if (!user) {
        errors.username = 'User not found'
        return res.status(404).json(errors)
      }

      bcrypt.compare(password, user.password)
        .then(isMatch => {
          const payload = { id: user.id, username: user.username }
          if (isMatch) {
            jwt.sign(payload, keys.secretOrKey, { expiresIn: 3600 },
              (err, token) => res.json({ success: true, token: 'Bearer ' + token })
            )
          } else {
            return res.status(400).json({ password: 'Incorrect password' })
          }
        })
    })
})

module.exports = router